### ISSUE TITLE
pip install "--editable=git+https://github.com/huggingface/transformers.git@372a5c1ceec49b52c503707e9657bfaae7c236a0#egg=pytorch_pretrained_bert" --no-cache-dir

### ISSUE THREAD

**Issue by HelloMark97** [medtray/StruBERT#2]
Hello,i would like to ask you the version of this transformer,i can not download.

**Comment by medtray** [comment]
Hello, it should be the same as in https://github.com/facebookresearch/TaBERT/blob/main/scripts/env.yml . 
Try pytorch-pretrained-bert 0.6.2 and transformers 2.8.0

**Comment by HelloMark97** [comment]
Thank you,i will try transformers 2.8.0 and tell you results later.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "medtray/StruBERT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月12日(星期六) 上午10:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [medtray/StruBERT] pip install ***@***.***#egg=pytorch_pretrained_bert" --no-cache-dir (Issue #2)





 
Hello, it should be the same as in https://github.com/facebookresearch/TaBERT/blob/main/scripts/env.yml . Try transformers 2.8.0 and let me know.
